import type { Deal } from "./types";

function iso(offset = 0) {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() + offset);
  return d.toISOString().slice(0, 10);
}

export const demoDeals: Deal[] = [
  {
    id: "demo-nike",
    brand: "Nike",
    campaign: "Fall Running Launch",
    value: 1800,
    currency: "USD",
    status: "Payment Pending",
    platform: "Instagram",
    dueDate: iso(-12),
    paymentDue: iso(-4),
    paymentStatus: "Overdue",
    rightsEnd: iso(18),
    rightsType: "Paid social · 90 days",
    deliverable: "1 Reel + 3 Stories",
    email: "partnerships@nike.example",
    notes: "90-day paid social usage. Renewal conversation should begin 14 days before expiry.",
  },
  {
    id: "demo-gymshark",
    brand: "Gymshark",
    campaign: "Training Essentials",
    value: 1200,
    currency: "USD",
    status: "Published",
    platform: "TikTok",
    dueDate: iso(-3),
    paymentDue: iso(12),
    paymentStatus: "Pending",
    rightsEnd: iso(5),
    rightsType: "Organic + paid · 60 days",
    deliverable: "2 TikToks",
    email: "creator@gymshark.example",
    notes: "Potential renewal after paid usage period.",
  },
  {
    id: "demo-notion",
    brand: "Notion",
    campaign: "Creator Workflow",
    value: 2500,
    currency: "USD",
    status: "Content Due",
    platform: "YouTube",
    dueDate: iso(1),
    paymentDue: iso(35),
    paymentStatus: "Pending",
    rightsEnd: iso(90),
    rightsType: "Organic · 90 days",
    deliverable: "60s integration",
    email: "brand@notion.example",
    notes: "Brand approval required before publishing.",
  },
  {
    id: "demo-squarespace",
    brand: "Squarespace",
    campaign: "Portfolio Refresh",
    value: 2200,
    currency: "USD",
    status: "Negotiating",
    platform: "YouTube",
    dueDate: iso(14),
    paymentDue: iso(44),
    paymentStatus: "Pending",
    rightsEnd: iso(120),
    rightsType: "Organic · 120 days",
    deliverable: "90s integration",
    email: "creator@squarespace.example",
    notes: "Rate negotiation in progress.",
  },
  {
    id: "demo-adobe",
    brand: "Adobe",
    campaign: "Creative Cloud UGC",
    value: 950,
    currency: "USD",
    status: "Paid",
    platform: "UGC",
    dueDate: iso(-45),
    paymentDue: iso(-15),
    paymentStatus: "Paid",
    rightsEnd: iso(28),
    rightsType: "Paid social · 90 days",
    deliverable: "3 UGC videos",
    email: "ugc@adobe.example",
    notes: "Payment received.",
  },
];
